### ISSUE TITLE
probar task list

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/pruebas_de_concepto#2]
- [ ] ver cómo se pone
- [ ] ver si se completa
- [ ] ver si funciona
